### ISSUE TITLE
Feature Request: multi-arch images (amd64, arm64)

### ISSUE THREAD

**Issue by gclawes** [kubealex/k8s-mediaserver-operator#1]
Raspberry Pi clusters are a good use case, support for arm64 images are required to do this.  `quay.io/operator-framework/helm-operator` has arm64 manifests in addition to amd64.

**Comment by veenarm** [comment]
Added to this:
armhf  arm32v7-latest

Would be great :)

**Comment by veenarm** [comment]
Only arm64 support seems to be added for the operator, wont boot on arm32v7 (default in Pi4)

**Comment by kubealex** [comment]
@veenarm at this time, no support is given from operatorSDK to armv7. I'd suggest to go for a Debian Build that allows to use arm64.

**Comment by gclawes** [comment]
Ubuntu Core works great on RPi4 for arm64

**Comment by veenarm** [comment]
Linux  5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux

I'll look up updating one of the app-nodes and target it for the operator to try it out, probably going to setup a x64 node anyway that's more powerful to run Plex, as plex sometimes on the pi is a bit slow for 1080p+ videos.
