### ISSUE TITLE
[BR]

### ISSUE THREAD

**Issue by mulbane** [kubealex/k8s-mediaserver-operator#12]
**Describe the bug**
I'm not sure this is a bug, but don't think it's a feature request.  The ingress isn't being created on my implementation, and I just wanted to know if this is expected.  If I need to set up an ingress on my own, that's fine but I'm not seeing it attached.  I'm also not seeing the PVC, but I'm new to helm charts and kubernetes overall.

**Comment by mulbane** [comment]
Yeah, I switched to NFS, still trying to figure out why it's not working now... I actually got it working with longhorn but retained volumes weren't re-attaching when I re-deployed, so I would lose my configs every time unfortunately.

**Comment by kubealex** [comment]
I removed the possibility to specify NFS volumes manually to have the PV created. 

A PV or a StorageClass linked to a provisioner are needed in order to create the PVC.
