### ISSUE TITLE
[BR]

### ISSUE THREAD

**Issue by smtrock** [kubealex/k8s-mediaserver-operator#15]
**Describe the bug**

**To Reproduce**
- running minikube on windows subsystem for linux following followed https://danieliser.com/setup-minikube-on-wsl2-for-windows-10/ 
- clone repo 
-  run kubectl apply -f k8s-mediaserver-operator.yml

**Expected behavior**

expecting to get to any of the referenced links 
http://k8s-mediaserver.k8s.test/sonarr
http://k8s-mediaserver.k8s.test/radarr
http://k8s-mediaserver.k8s.test/transmission
http://k8s-mediaserver.k8s.test/jackett

http://k8s-plex.k8s.test/

get DNS_PROBE_FINISHED_NXDOMAIN error failed to reach resource, could this be a DNS or HOSTS entry missing, in k8 dashboard all seems well pod and svcs get deployed. 

I am certainly a noob with K8s and have a gap in my knowledge on the networking components.  

**Screenshots**

**Environment:**
 - K8s version:
 Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
 - CNI Plugin:
 - CSI Type:

**Additional context**

**Comment by kubealex** [comment]
Hi, I suggest you to take a look at this (https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/) to understand how to start using ingresses in minikube. 
I am closing this one as it not related to the project itself.
