### ISSUE TITLE
Can't init Plex media server

### ISSUE THREAD

**Issue by ilanKushnir** [kubealex/k8s-mediaserver-operator#21]
First of all, thank you @kubealex  so much for these awesome configurations! it saved me so much time!!!

**Describe the bug**
I don't get the Plex initial "server setup wizard"
and can't connect to the server which should run on `plex.[MY_MASTER_NODE_IP].nip.io`
I'm able to see all the dashboards (including Plex's), connected successfully `Sonarr & Radarr` to => `Jackett & Transmission`
but when testing the connection from `Sonarr & Radarr` to `plex` it fails

**To Reproduce**
those are the exact changes:
https://github.com/kubealex/k8s-mediaserver-operator/compare/kubealex:master...ilanKushnir:master

**Expected behavior**
* To setup Plex media server (via the initial wizard)
and not skipping - instead, I login and see the Plex main page: 
* To connect to the created server successfully via Sonarr and Radarr, failed with both `32400` and `80`

**Screenshots**
[Plex dashboard after login](https://imgur.com/a/syqiaGo)
[Failing to connect in Sonaar (tried also port 80)](https://imgur.com/a/sQcrApp)

**Environment:**
 - K8s version: K3S

**Comment by kubealex** [comment]
Hi @ilanKushnir, I'm spotting a couple of issues here.
1) have you set the plex claim id in the CR? It is needed to claim your server and trigger the customization process you are referring to.
2) Once you managed to claim your server, can you try again using both the nip.io hostname or also the name of the k8s service?

Thank you!

**Comment by ilanKushnir** [comment]
Hi @kubealex thanks for the fast response!

1. yes, I've updated the plex claim token just before applying the yaml (got the token from: https://plex.tv/claim)
2. tried all possible variations of hosts 😅, what do you mean by the k8s service? the ingress is pointing to it

I'm almost sure that the problem is that the initial setup isn't showing me the server setup and gets my straight into the main dashboard after logging in...

**Comment by kubealex** [comment]
1) I suggest to completely recreate the resources with a new claim
2) When in *arr you can add the plex reference using the service name (servicename or servicename.namespace.svc.cluster.local) to use local resolution and avoid hopping.

**Comment by ilanKushnir** [comment]
will try that and update
thank a lot @kubealex !!

**Comment by ilanKushnir** [comment]
> 1. I suggest to completely recreate the resources with a new claim
> 2. When in *arr you can add the plex reference using the service name (servicename or servicename.namespace.svc.cluster.local) to use local resolution and avoid hopping.

@kubealex that helped my a lot configuring all the the other services
and Plex was fixed after I created a IngressRoute

**Comment by kubealex** [comment]
I'm really glad it helped!! Enjoy your mediaserver then 😜😜😜😜
