### ISSUE TITLE
[FR] Having different PV for each tool

### ISSUE THREAD

**Issue by InputObject2** [kubealex/k8s-mediaserver-operator#26]
**Is your feature request related to a problem? Please describe.**
When using the current setup, all the tools are configured directly with the same persistent volume, where the media, configs and apparently sqlite databases are created. This causes issues for some storage backends that might not be well suited to run databases, such as NFS or SMB shares.

**Describe the solution you'd like**
I'd like to add a specific PV/PVC for each tool, in addition to the main "media" PV where all the movies and shows are stored.

**Describe alternatives you've considered**
There is already the additional PV field under `spec.general.storage.volumes` but this is not really helpful to set specific mounts on specific tools. 

**Additional context**
Jackett, transmission, plex and sabnzbd seem to work as they all just rely on flat files, while sonarr and radarr run sqlite instances and rely on those.

I'm opening this issue for the discussion, I'll bring the changes (or at least the way I see them) in a PR if we define a good retro-compatible way to do this.

**Comment by freakadell** [comment]
Any progress on this? Ive been playing around and not yet sure how to accomplish this as im really noob at this.
But here are couple of ideas i am trying:
Set up local volume on specific node and schedule Sonarr/Raddar on this node.
Longhorn StorageClass on specific node and schedule services on that node.
While keeping media on NFS.

Currently my biggest knowledge cap is how to apply changes in *-resources.yml files.

For now im unable to get Sonarr/Radarr running while conf is on NFS. Manages to do it only once.

**Comment by InputObject2** [comment]
I didn't start, in fact I completely forgot about it. I have some ideas, I'll make a PR soon-ish with the changes, should be pretty straightforward.

**Comment by freakadell** [comment]
@kubealex any chance of reviewing/approving this?

**Comment by kubealex** [comment]
Thanks a lot @InputObject2! Sorry for the late reply but I didn't have the chance to test it. 
Expect a merge in the next hours or so 👍👍

**Comment by kubealex** [comment]
@InputObject2 did you have the chance to review the PR comments I made?

**Comment by kubealex** [comment]
Merged!
