### ISSUE TITLE
[BR] Applying k8s-mediaserver.yml doesn't reliably create anything

### ISSUE THREAD

**Issue by ouberlord** [kubealex/k8s-mediaserver-operator#27]
**Describe the bug**
When running `kubectl apply -f k8s-mediaserver.yml` within the default namespace, some times it immediately begins to then create all of the expected deployments, services, pods, etc.  Other times it simply outputs "k8smediaserver.kubealex.com/k8smediaserver created" and does nothing else.

**To Reproduce**
- Run `kubectl apply -f k8s-mediaserver.yml`
- Run `kubectl get all`
- Verify that no services, pods, replicasets, etc. are being created:
NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.152.183.1   <none>        443/TCP   29h

**Expected behavior**
The following should be created and viewable via running `kubectl get all` after running `kubectl apply -f k8s-mediaserver.yml`:
NAME                                READY   STATUS    RESTARTS   AGE
pod/transmission-55c766c788-k72ps   0/1     Pending   0          106s
pod/jackett-5fc4cccd5d-q4bcq        0/1     Pending   0          105s
pod/radarr-bccc8b58f-ggwc7          0/1     Pending   0          106s
pod/sabnzbd-7fd7fb4fd5-2dj8p        0/1     Pending   0          106s
pod/plex-694949d5d7-flx29           0/1     Pending   0          106s
pod/sonarr-756d7cfb87-95cgn         0/1     Pending   0          106s

NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE
service/kubernetes              ClusterIP   10.152.183.1     <none>        443/TCP     29h
service/sabnzbd-https           ClusterIP   10.152.183.172   <none>        9090/TCP    109s
service/sonarr                  ClusterIP   10.152.183.67    <none>        8989/TCP    109s
service/radarr                  ClusterIP   10.152.183.42    <none>        7878/TCP    108s
service/transmission            ClusterIP   10.152.183.136   <none>        9091/TCP    108s
service/transmission-peer-tcp   ClusterIP   10.152.183.126   <none>        51413/TCP   107s
service/transmission-peer-udp   ClusterIP   10.152.183.17    <none>        51413/UDP   107s
service/jackett                 ClusterIP   10.152.183.144   <none>        9117/TCP    107s
service/plex                    ClusterIP   10.152.183.70    <none>        32400/TCP   107s
service/sabnzbd                 ClusterIP   10.152.183.221   <none>        8080/TCP    106s

NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/transmission   0/1     1            0           106s
deployment.apps/radarr         0/1     1            0           106s
deployment.apps/sabnzbd        0/1     1            0           106s
deployment.apps/plex           0/1     1            0           106s
deployment.apps/sonarr         0/1     1            0           106s
deployment.apps/jackett        0/1     1            0           106s

NAME                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/transmission-55c766c788   1         1         0       106s
replicaset.apps/sabnzbd-7fd7fb4fd5        1         1         0       106s
replicaset.apps/radarr-bccc8b58f          1         1         0       106s
replicaset.apps/plex-694949d5d7           1         1         0       106s
replicaset.apps/sonarr-756d7cfb87         1         1         0       106s
replicaset.apps/jackett-5fc4cccd5d        1         1         0       106s

**Environment:**
 - K8s version: v1.24.0-2+59bbb3530b6769 (running via microk8s)

**Comment by ouberlord** [comment]
Worth noting that I have been able to get `kubectl apply -f k8s-mediaserver.yml` to work a couple of times, thus the output for what is expected, but I can't seem to make it work reliably.  I've also tried completely deleting the operator side via `kubectl delete -f k8s-mediaserver-operator.yml` before then reapplying that and then k8s-mediaserver.yml, which results in no change.

**Comment by kubealex** [comment]
Hi @ouberlord thank you for reporting this.
Can you please post the logs of the operator when you see no resources being created?
Thank you!!

**Comment by ouberlord** [comment]
I certainly can.  How can I do so?  I've been poking around using kubectl describe, but haven't found anything noteworthy.  If I turn on verbose output I get the following, but I suspect this isn't what you are asking for.

`root@kubernetes-test:~/github/k8s-mediaserver-operator# microk8s kubectl apply -f k8s-mediaserver.yml -v=7
I0612 16:45:29.089544   24595 loader.go:372] Config loaded from file:  /var/snap/microk8s/3272/credentials/client.config
I0612 16:45:29.089930   24595 round_trippers.go:463] GET https://127.0.0.1:16443/openapi/v2?timeout=32s
I0612 16:45:29.089957   24595 round_trippers.go:469] Request Headers:
I0612 16:45:29.089965   24595 round_trippers.go:473]     Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I0612 16:45:29.089973   24595 round_trippers.go:473]     User-Agent: kubectl/v1.24.0 (linux/amd64) kubernetes/59bbb35
I0612 16:45:29.089979   24595 round_trippers.go:473]     Authorization: Bearer <masked>
I0612 16:45:29.107032   24595 round_trippers.go:574] Response Status: 200 OK in 17 milliseconds
I0612 16:45:29.174564   24595 round_trippers.go:463] GET https://127.0.0.1:16443/apis/kubealex.com/v1/namespaces/k8s-mediaserver/k8smediaservers/k8smediaserver
I0612 16:45:29.174597   24595 round_trippers.go:469] Request Headers:
I0612 16:45:29.174605   24595 round_trippers.go:473]     Accept: application/json
I0612 16:45:29.174618   24595 round_trippers.go:473]     User-Agent: kubectl/v1.24.0 (linux/amd64) kubernetes/59bbb35
I0612 16:45:29.174627   24595 round_trippers.go:473]     Authorization: Bearer <masked>
I0612 16:45:29.176924   24595 round_trippers.go:574] Response Status: 404 Not Found in 2 milliseconds
I0612 16:45:29.177086   24595 round_trippers.go:463] GET https://127.0.0.1:16443/api/v1/namespaces/k8s-mediaserver
I0612 16:45:29.177114   24595 round_trippers.go:469] Request Headers:
I0612 16:45:29.177121   24595 round_trippers.go:473]     Accept: application/json
I0612 16:45:29.177164   24595 round_trippers.go:473]     User-Agent: kubectl/v1.24.0 (linux/amd64) kubernetes/59bbb35
I0612 16:45:29.177185   24595 round_trippers.go:473]     Authorization: Bearer <masked>
I0612 16:45:29.178858   24595 round_trippers.go:574] Response Status: 200 OK in 1 milliseconds
I0612 16:45:29.179100   24595 round_trippers.go:463] POST https://127.0.0.1:16443/apis/kubealex.com/v1/namespaces/k8s-mediaserver/k8smediaservers?fieldManager=kubectl-client-side-apply&fieldValidation=Strict
I0612 16:45:29.179126   24595 round_trippers.go:469] Request Headers:
I0612 16:45:29.179133   24595 round_trippers.go:473]     User-Agent: kubectl/v1.24.0 (linux/amd64) kubernetes/59bbb35
I0612 16:45:29.179148   24595 round_trippers.go:473]     Accept: application/json
I0612 16:45:29.179152   24595 round_trippers.go:473]     Content-Type: application/json
I0612 16:45:29.179176   24595 round_trippers.go:473]     Authorization: Bearer <masked>
I0612 16:45:29.190877   24595 round_trippers.go:574] Response Status: 201 Created in 11 milliseconds
k8smediaserver.kubealex.com/k8smediaserver created
I0612 16:45:29.191279   24595 apply.go:460] Running apply post-processor function`

**Comment by kubealex** [comment]
You can try with:
`kubectl logs <operatorPodName> -n <operatorPodNamespace>
`
or if you want to 'tail' the logs add '-f' to the kubectl logs command.

**Comment by ouberlord** [comment]
Ah, understood.  Nothing out of it seems to indicate it's really tried anything yet.

```shell
root@kubernetes-test:~/github/k8s-mediaserver-operator# microk8s kubectl logs k8s-mediaserver-operator-controller-manager-54c6cfcf6d-dn24q -n k8s-mediaserver-operator-system
Defaulted container "kube-rbac-proxy" out of: kube-rbac-proxy, manager
I0612 16:31:51.401215       1 main.go:190] Valid token audiences:
I0612 16:31:51.401281       1 main.go:262] Generating self signed cert as no cert is provided
I0612 16:31:51.538876       1 main.go:311] Starting TCP socket on 0.0.0.0:8443
I0612 16:31:51.539561       1 main.go:318] Listening securely on 0.0.0.0:8443
```

**Comment by ouberlord** [comment]
Oh, wait a minute.  So I saw that was just defaulting to the proxy container logs.  When I checked the manager logs, I get this:

```shell
root@kubernetes-test:~/github/k8s-mediaserver-operator# microk8s kubectl logs k8s-mediaserver-operator-controller-manager-54c6cfcf6d-dn24q -c manager -n k8s-mediaserver-operator-system --tail=5
{"level":"error","ts":1655053648.9417362,"logger":"controller.k8smediaserver-controller","msg":"Reconciler error","name":"k8smediaserver","namespace":"k8s-mediaserver","error":"failed to install release: rendered manifests contain a resource that already exists. Unable to continue with install: PersistentVolumeClaim \"mediaserver-pvc\" in namespace \"k8s-mediaserver\" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key \"app.kubernetes.io/managed-by\": must be set to \"Helm\"; annotation validation error: missing key \"meta.helm.sh/release-name\": must be set to \"k8smediaserver\"; annotation validation error: missing key \"meta.helm.sh/release-namespace\": must be set to \"k8s-mediaserver\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":1655054649.706211,"logger":"helm.controller","msg":"Release failed","namespace":"k8s-mediaserver","name":"k8smediaserver","apiVersion":"kubealex.com/v1","kind":"K8SMediaserver","release":"k8smediaserver","error":"failed to install release: rendered manifests contain a resource that already exists. Unable to continue with install: PersistentVolumeClaim \"mediaserver-pvc\" in namespace \"k8s-mediaserver\" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key \"app.kubernetes.io/managed-by\": must be set to \"Helm\"; annotation validation error: missing key \"meta.helm.sh/release-name\": must be set to \"k8smediaserver\"; annotation validation error: missing key \"meta.helm.sh/release-namespace\": must be set to \"k8s-mediaserver\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":1655054649.715656,"logger":"controller.k8smediaserver-controller","msg":"Reconciler error","name":"k8smediaserver","namespace":"k8s-mediaserver","error":"failed to install release: rendered manifests contain a resource that already exists. Unable to continue with install: PersistentVolumeClaim \"mediaserver-pvc\" in namespace \"k8s-mediaserver\" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key \"app.kubernetes.io/managed-by\": must be set to \"Helm\"; annotation validation error: missing key \"meta.helm.sh/release-name\": must be set to \"k8smediaserver\"; annotation validation error: missing key \"meta.helm.sh/release-namespace\": must be set to \"k8s-mediaserver\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":1655055650.4039044,"logger":"helm.controller","msg":"Release failed","namespace":"k8s-mediaserver","name":"k8smediaserver","apiVersion":"kubealex.com/v1","kind":"K8SMediaserver","release":"k8smediaserver","error":"failed to install release: rendered manifests contain a resource that already exists. Unable to continue with install: PersistentVolumeClaim \"mediaserver-pvc\" in namespace \"k8s-mediaserver\" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key \"app.kubernetes.io/managed-by\": must be set to \"Helm\"; annotation validation error: missing key \"meta.helm.sh/release-name\": must be set to \"k8smediaserver\"; annotation validation error: missing key \"meta.helm.sh/release-namespace\": must be set to \"k8s-mediaserver\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":1655055650.4517894,"logger":"controller.k8smediaserver-controller","msg":"Reconciler error","name":"k8smediaserver","namespace":"k8s-mediaserver","error":"failed to install release: rendered manifests contain a resource that already exists. Unable to continue with install: PersistentVolumeClaim \"mediaserver-pvc\" in namespace \"k8s-mediaserver\" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key \"app.kubernetes.io/managed-by\": must be set to \"Helm\"; annotation validation error: missing key \"meta.helm.sh/release-name\": must be set to \"k8smediaserver\"; annotation validation error: missing key \"meta.helm.sh/release-namespace\": must be set to \"k8s-mediaserver\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227"}
```

**Comment by ouberlord** [comment]
Yep, that was entirely the issue.  I misunderstood the Quick Start text of "Being able to provision an RWX PV where to store configurations" to mean that the PVC or volume had to be created first.  After removing it, then rerunning things I got much farther with all the objects being created as one would expect.  Sometimes it's the simple things.  Thanks for the help!
