### ISSUE TITLE
Does Helm Install alone work without installing this project as an operator?

### ISSUE THREAD

**Issue by chinmaya-n** [kubealex/k8s-mediaserver-operator#34]
Hi,

I see that this project is an k8s operator based on the name & instructions. However, the README does speak about using Helm. I see a `helm-charts` directory and wondering if I can solely install it with Helm without having to install this as an operator.

I personally disagree with the design choice of using an operator rather than making it a helm app. However, I understand that this has been done to learn by the author.

Thanks,
Chinmaya

**Comment by kubealex** [comment]
Hi, thank you for your feedback :)
The helm chart backing the operator is available at [](https://github.com/kubealex/k8s-mediaserver-helm).

Have a great day!
