### ISSUE TITLE
[FR] Performance guidance

### ISSUE THREAD

**Issue by dsfrederic** [kubealex/k8s-mediaserver-operator#35]
**Is your feature request related to a problem? Please describe.**
My plex server is quite slow and unresponsive. 

**Describe the solution you'd like**
I would like to get some guidance on what the minimum/best specs are for deploying this in the main cloud providers. (Azure/AWS/...)

This can be broken down into multiple sections: 
Storage 
Networking 
VM Size

Questions I want to raise: 
- Would it help to replicate some of the pods?
-  Would it be better to have your downloads on a second node? 
- How to minimize read/write operations?

**Comment by Tylermarques** [comment]
Hi @dsfrederic, 

For minimum settings, you should look at the settings recommended by each of the pieces of software. For example, here is [Plex's minimum requirements page](https://support.plex.tv/articles/200375666-plex-media-server-requirements/).

You should not need to replicate pods. One replica is enough, given the correct hardware. Minimizing r/w operations is out of scope of this project, as this only implements other open source software.

Seeing as this project can be deployed in many different ways, it would be very difficult for us to debug your particular issues. If you are experiencing poor performance with playback from Plex, it may be that you are [transcoding on a CPU](https://support.plex.tv/articles/200250377-transcoding-media/).
