### ISSUE TITLE
Error: unknown flag: --metrics-bind-address

### ISSUE THREAD

**Issue by dermot-mcg** [kubealex/k8s-mediaserver-operator#36]
**Describe the bug**
After running `kubectl apply -f k8s-mediaserver-operator-arm64.yml` on a raspberry pi cluster at home, I see the operator pod displaying a `CrashLoopBackOff ` error. Investigating the logs I see the following error: `Error: unknown flag: --metrics-bind-address`.  I am running K3s on the cluster but I don't think that should be an issue with this error? When deleting the apply, removing the line in the yaml, and running again, I get a similar error with `Error: unknown flag: --leader-elect`. Seems the args may not be valid?

**To Reproduce**
- Run the code on a raspberry pi 

**Expected behavior**
Pod launches without error

**Comment by kubealex** [comment]
Thank you for reporting this, it was a regression introduced with the latest manifest.
It is fixed with #37
