### ISSUE TITLE
[BR] Docker image tags set to devel/latest

### ISSUE THREAD

**Issue by JosefWN** [kubealex/k8s-mediaserver-operator#65]
How do we know that the `latest` images are stable, both on their own and in concert with one another? That will depend entirely on timing. For some users it will work, for some it won't because breaking changes have been released (Sonarr v4 coming up for example), or because of bugs in stable releases.

I think it would make sense to pin the docker image versions for every release, and test to see that it works decently. Alternatively, if it takes too much time, add a warning at the top of the README saying that you need to pin these versions yourself. This is why helm charts have an `appVersion` for example, indicating a strong coupling between chart version X and app version Y.

> The operator and the CR are already configured with some defaults settings to make you jump and go with it.

Texts like these imply the very opposite, that it comes configured out of the box.

**Comment by kubealex** [comment]
hi @JosefWN,

It actually is a good idea, we could simply add a configurable tag for each 'product' and let the user configure it. 
The different tools travel at very different speeds, and image tags are even faster, so it would not be ideal to stick a release to the underlying tools version.

But I get your point and I will probably start working on improving this one.

Of course, if you want to contribute here, feel free to!

**Comment by kubealex** [comment]
Closing as we now have a configurable image/tag for each component, allowing an ad-hoc override.
Since the set of apps is growing fast and each tool has different release cycles, freezing a baseline could be potentially less convenient (CVEs, bugix, etc) than having latest by default and adapting that.
