### ISSUE TITLE
[FR] Helm repository

### ISSUE THREAD

**Issue by NigelVanHattum** [kubealex/k8s-mediaserver-operator#90]
**Is your feature request related to a problem? Please describe.**
There is a helm template located in this repository. My deployment is done via ArgoCD that requires a helm repository. 

**Describe the solution you'd like**
Have this repository also contain the helm repository, should be possible with github raw.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by reedjosh** [comment]
Yo! I'm kinda working on that. Just rather slow going.

See: https://github.com/kubealex/k8s-mediaserver-operator/issues/87

I had similar thoughts.

You can point to the chart directory for now and it works with ArgoCD just fine, but is a little clunky.

**Comment by NigelVanHattum** [comment]
Closing this issue, let's follow the progress via #87
